image: Visual Studio 2022

build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
    - PYTHON_VERSION: 3.8
      MINICONDA: C:\Miniconda38-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% scipy nose"
  - activate test-environment
  - pip install .
  - pip install tensorflow scipy --user --upgrade --force-reinstall

test_script:
  - nosetests
